# Étape 1 : build de l'app React
FROM --platform=linux/amd64 node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# Étape 2 : image nginx optimisée pour React
FROM --platform=linux/amd64 nginx:alpine
# Copier la config personnalisée de nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copier le build React généré
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]