global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  # Jenkins metrics
  - job_name: 'jenkins'
    metrics_path: '/prometheus'  # Jenkins Prometheus plugin endpoint
    static_configs:
      - targets: ['jenkins:8080']  # Nom du conteneur Docker

  # cAdvisor metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Nom du conteneur Docker