pipeline {
  agent {
    docker {
      image 'node:18'
      args '-u root' // pour les permissions si besoin
    }
  }

  environment {
    NODE_ENV = 'test'
    SONARQUBE_URL = 'http://sonarqube:9000'
    SONARQUBE_TOKEN = credentials('sonarqube-token')
    VPS_USER = 'root'
    VPS_HOST = '161.97.76.223'
    REMOTE_PROJECT_PATH = '/PROJET/THETIPTOP_GAME'
    SYSTEM_DEBUG = 'true'
  }

  stages {
    stage('Checkout Code') {
      steps {
        script {
          checkout([
            $class: 'GitSCM',
            branches: [[name: "*/${env.BRANCH_NAME}"]],
            extensions: [[$class: 'CleanBeforeCheckout']],
            userRemoteConfigs: [[url: 'https://github.com/Acharaf-Dev/THETIPTOP_GAME.git']]
          ])

          switch (env.BRANCH_NAME) {
            case 'main':
              echo "🔴 Déploiement en Production"
              env.DOCKER_IMAGE = "thetiptop_game/backend:prod-${GIT_COMMIT}"
              break
            case 'preprod':
              echo "🟡 Déploiement en Préproduction"
              env.DOCKER_IMAGE = "thetiptop_game/backend:preprod-${GIT_COMMIT}"
              break
            case 'develop':
            case 'test':
            case 'testunit':
              echo "🟢 Branche de test/développement"
              env.DOCKER_IMAGE = "thetiptop_game/backend:dev-${GIT_COMMIT}"
              break
            default:
              error "❌ Branche non supportée : ${env.BRANCH_NAME}"
          }
        }
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('backend') {
          script {
            sh 'npm install --include=
