FROM node:18

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers de l'application dans l'image Docker
COPY . .

# Exposer le port (modifie selon le port que tu utilises pour le SSR)
EXPOSE 4200

# Construire l'application
RUN npm run build

# Lancer l'application
CMD ["npm", "start"]
