# frontend/Dockerfile.ssr
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:18
WORKDIR /app
COPY --from=builder /app /app
RUN npm install express react react-dom react-router-dom
COPY .env.ssr .env
EXPOSE 3000
CMD ["node", "ssr/server.js"]
